version: 2.1


orbs:
  win: circleci/windows@2.4.1

commands:
  build:
    steps:
      - checkout
      - run:
          name: do stuff
          command: |
            Invoke-WebRequest 'https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.ps1' -OutFile 'dotnet-install.ps1';
            ./dotnet-install.ps1 -InstallDir '~/.dotnet' -Version '6.0.0';
      - run:
          name: dotnet publish
          command: |
            mkdir /publish
            dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -p:Version=$env:CIRCLE_TAG -o /publish
            ls /publish/publish
  publish:
    steps:
      - run:
          name: Download github-release
          shell: bash.exe
          command: |
            curl -L --output github-release.zip https://github.com/github-release/github-release/releases/download/v0.8.1/windows-amd64-github-release.zip
            unzip -u -d C:/github-release github-release.zip
      - run:
          name: zip release
          command: |
            tar.exe -a -c -f C:\publish\busylight-client.zip C:\publish\busylight-client.exe C:\publish\appsettings.json
      - run:
          name: Create Github releases
          command: |
            C:\github-release\bin\windows\amd64\github-release upload --user Gaardsholt --repo busylight-client --tag $env:CIRCLE_TAG --name "busylight-client.zip" --file "C:\publish\busylight-client.zip"

jobs:
  build:
    executor: win/default
    steps:
      - build
      
  publish:
    executor: win/default
    steps:
      - build
      - publish

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: gaardsholt
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /^[0-9]+(\.[0-9]+)*(-.*)*$/
  build-n-publish:
    jobs:
      - publish:
          context: gaardsholt
          filters:
            tags:
              only: /^[0-9]+(\.[0-9]+)*(-.*)*$/
            branches:
              ignore: /.*/