version: 2.1


orbs:
  win: circleci/windows@2.4.0

commands:
  build:
    steps:
      - checkout
      - run:
          name: dotnet publish
          command: |
            mkdir /publish
            dotnet publish -r win-x64 -c Release -p:PublishSingleFile=true -p:PublishTrimmed=true -o /publish
            ls /publish
  publish:
    steps:
      - run:
          name: Download ghr
          command: |
            curl -L --output ghr.zip https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_windows_386.zip
            unzip -u d C:\ghr ghr.zip
      - run:
          name: zip release
          command: |
            tar.exe -a -c -f C:\publish\busylight-client.zip C:\publish\busylight-client.exe C:\publish\appsettings.json
      - run:
          name: Create Github releases
          command: |
            C:\ghr_v0.13.0_windows_386/ghr.exe -replace $CIRCLE_TAG C:\publish\busylight-client.zip

jobs:
  build:
    executor: win/default
    steps:
      - build
      - run:
          name: list stuff
          command: |
            ls /publish
      
  publish:
    executor: win/default
    steps:
      - build
      - publish

workflows:
  version: 2
  # build:
  #   jobs:
  #     - build:
  #         context: gaardsholt
  #         filters:
  #           branches:
  #             only: /.*/
  #           tags:
  #             ignore: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
  build-n-publish:
    jobs:
      - publish:
          context: gaardsholt
          # filters:
          #   tags:
          #     only: /^v([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-]+)?$/
          #   branches:
          #     ignore: /.*/